repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: ['--branch', 'master']

- repo: local
  hooks:

    - id: isort
      name: isort
      entry: isort
      files: ^(bot/|core/|src/)
      language: system
      types: [python]
      args: ["--profile", "black", --line-length=79]

    - id: flake8
      name: flake8
      entry: flake8
      files: ^(bot/|core/|src/)
      language: system
      types: [python]
      args: [--config, setup.cfg]
