FROM python:3.12-bookworm

WORKDIR /app

# Копируем требования и устанавливаем зависимости
COPY requirements.txt .
RUN pip3 install -r requirements.txt --no-cache-dir

# Копируем исходники в контейнер
COPY src/ .

# Команда для запуска FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]