version: '3.8'
name: providenie

services:
  app:
    build: ../src
    restart: unless-stopped
    environment:
      - RUN_IN_DOCKER=1
      - TZ=Europe/Moscow
    env_file:
      - ./.env
    volumes:
      - ./logs/:/app/bot/.data/

    depends_on:
      - db

  nginx:
    image: nginx:1.27.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    env_file:
      - path: ./.env
        required: true
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_logs:/var/log/postgresql
    ports:
      - 5432:5432

volumes:
  db_data:
  db_logs:
