# HANDLERS PREFIX
MENU = "MENU"
OPTION = "OPTION"
ASK = "ASK"

# MENU or OPTION
NAME = "NAME"
FORM_HEADER = "FORM_HEADER"
DESCRIPTION = "DESCRIPTION"
BUTTON_TEXT = "BUTTON_TEXT"
LINK = "LINK"
OPTIONS = "OPTIONS"
CUSTOM_MODEL = "CUSTOM_MODEL"

# FORM INFO
MODEL = "MODEL"
FIELDS = "FIELDS"

# FORM
FORM = "FORM"
DATA = "DATA"
SHOW_DATA = "SHOW_DATA"
FIELD_INDEX = "FIELD_INDEX"
FIELD_EDIT = "FIELD_EDIT"
RESPONSE = "RESPONSE"

# QUESTIONS
TITLE = "TITLE"
TEXT = "TEXT"
HINT = "HINT"
