from telegram.ext import ConversationHandler


"""General keys."""
END = ConversationHandler.END
SENT = "SENT"
START_OVER = "START_OVER"
LEVEL = "LEVEL"
FEATURES = "FEATURES"
CURRENT_FEATURE = "CURRENT_FEATURE"

NAME = "NAME"
BIRTHDAY = "BIRTHDAY"
CITY = "CITY"
PHONE = "PHONE"
EMAIL = "EMAIL"
MESSAGE = "MESSAGE"
THEME = "THEME"

"""Main menu keys."""
CHATS = "CHATS"
REQUEST = "REQUEST"
ADD_VOLUNTEER = "ADD_VOLUNTEER"
TELL_ABOUT_FUND = "TELL_ABOUT_FUND"
DONATION = "DONATION"
EVENTS = "EVENTS"
ASK_QUESTION = "ASK_QUESTION"
ABOUT = "ABOUT"

"""Volunteer keys."""
VOLUNTEER = "VOLUNTEER"
EDIT_VOLUNTEER = "EDIT_VOLUNTEER"
SEND_VOLUNTEER = "SEND_VOLUNTEER"

"""Ask a question keys."""
QUESTION = "QUESTION"
EDIT_QUESTION = "EDIT_QUESTION"
SEND_QUESTION = "SEND_QUESTION"

"""Tell about fund."""
WEBSITE = "WEBSITE"
VK = "VK"
INSTAGRAM = "INSTAGRAM"
FACEBOOK = "FACEBOOK"
TG_CHANNEL = "TG_CHANNEL"
TG_BOT = "TG_BOT"
