from telegram.ext import ConversationHandler


"""Константы ConversationHandler"""
(
    SELECTING_ACTION,
    CHATS,
    REQUEST,
    ADD_VOLUNTEER,
    TALK,
    DONATION,
    EVENTS,
    QUESTION,
    ABOUT,
) = map(chr, range(9))

(
    VOLUNTEER,
    ADDING_VOLUNTEER,
    ADDING_NAME,
    ADDING_BIRTHDAY,
    ADDING_CITY,
    ADDING_PHONE,
    ADDING_EMAIL,
    ADDING_MESSAGE,
    SHOWING_VOLUNTEER,
    EDIT_VOLUNTEER,
    VOLUNTEER_FEATURE,
    TYPING_VOLUNTEER,
    SEND_VOLUNTEER,
    VOLUNTEER_SENT,
    SENT,
) = map(chr, range(10, 25))

(STOPPING,) = map(chr, range(30, 31))

(
    START_OVER,
    CURRENT_FEATURE,
    LEVEL,
    FEATURES,
    NAME,
    BIRTHDAY,
    CITY,
    PHONE,
    EMAIL,
    MESSAGE,
) = map(chr, range(100, 110))

END = ConversationHandler.END

"""Константы чатов"""
(
    CHAT_BABY,
    CHAT_CHILD,
    CHAT_RETINOPATIA,
    CHAT_SHUNTATA,
    CHAT_GRANDMOTHERS,
    CHAT_CRY,
    CHAT_ANGELS,
    CHAT_RETINOPATIA_4_5,
    CHAT_PROBLEMS,
    CHAT_REHABILITATION,
    CHAT_TELECRAM,
) = map(chr, range(200, 211))

(
    # START_OVER,
    # STOPPING,
    # END,
    CHAT_FEATURE,
    CURRENT_CHAT,
    SELECTING_CHAT,
    # FEATURES,
    # CURRENT_FEATURE,
    ENTRY_CHAT,
    ENTERING_CHAT,
    CHAT_TYPING,
    CHAT_SHOWING,
    CHAT_DATA_EDIT,
    CHAT_SEND,
) = map(
    chr, range(220, 229)
)  # 234

(
    CHAT_PARENTS_NAME,
    CHAT_PARENTS_PHONE,
    CHAT_CHILD_NAME,
    CHAT_CHILD_BIRTHDAY,
    CHAT_CHILD_PLACE_BIRTHDAY,
    CHAT_CHILD_TERM,
    CHAT_CHILD_WEIGHT,
    CHAT_CHILD_HEIGHT,
    CHAT_CHILD_DIAGNOSE,
    CHAT_CHILD_OPERATION,
    CHAT_DATE_ADDRESS,
    CHAT_ABOUT_FOND,
) = map(chr, range(240, 252))


(
    CHAT_GETTING_PARENTS_SURNAME,
    CHAT_GETTING_PARENTS_PHONE,
    CHAT_GETTING_CHILD_NAME,
    CHAT_GETTING_CHILD_BIRTHDAY,
    CHAT_GETTING_CHILD_PLACE_BIRTHDAY,
    CHAT_GETTING_CHILD_TERM,
    CHAT_GETTING_CHILD_WEIGHT,
    CHAT_GETTING_CHILD_HEIGHT,
    CHAT_GETTING_CHILD_DIAGNOSE,
    CHAT_GETTING_CHILD_OPERATION,
    CHAT_GETTING_DATE_ADDRESS,
    CHAT_GETTING_ABOUT_FOND,
) = map(chr, range(260, 272))
