(
    LOOK_WORLD_PROGRAM, REABILITATION_PROGRAM,
    PSIHO_PROGRAM, KIND_LESSONS_PROGRAM, JOIN_BUTTON,
    MAIN_MENU, CONFIRM_AND_SEND, CHANGE_DATA,
    END_SECOND_LEVEL, EDIT_FIO_MOTHER, EDIT_PHONE, EDIT_EMAIL,
    EDIT_FIO_CHILD, EDIT_HOW_MANY_PEOPLE, EDIT_CITY,
    EDIT_ADDRESS, EDIT_BIRTHDAY, EDIT_PLACE_BIRTH,
    EDIT_BIRTH_DATE, EDIT_WEIGHT, EDIT_HEIGHT, EDIT_DIAGNOSIS,
    EDIT_HOW_FOUND, EDIT_WHICH_FOND, EDIT_WHICH_FOND_WAS_PREVIOUSLY,
) = range(0, 25)
