(
    JOIN_PROGRAM, FIO_MOTHER, RETURN_MOTHER_FIO,
    PHONE, EMAIL, FIO_CHILD, HOW_MANY_PEOPLE,
    CITY, ADDRESS, BIRTHDAY, PLACE_BIRTH,
    BIRTH_DATE, WEIGHT, HEIGHT, DIAGNOSIS,
    HOW_FOUND, WHICH_FUND, WHICH_FUND_WAS_PREVIOUSLY,
    EDIT_USER_DATА, END_FIRST_LEVEL, END_MAIN_MENU,
    GO_SECOND_LEVEL,
) = range(25, 47)
