"BASE"
BACK = "BACK"

"""MAIN MENU"""
SHARE_INFO = "SHARE_INFO"
MENU_ABOUT = "MENU_ABOUT"

"FORM"
FORM_MENU = "FORM_MENU"
DATA_COLLECT = "DATA_COLLECT"
DATA_SHOW = "DATA_SHOW"
DATA_EDIT = "DATA_EDIT"
DATA_SEND = "DATA_SEND"
