"BASE"
BACK = "BACK"

"""MAIN MENU"""
SHARE_INFO = "SHARE_INFO"
MENU_ABOUT = "MENU_ABOUT"

"FORM"
FORM_MENU = "FORM_MENU"
INFO_COLLECT = "INFO_COLLECT"
INFO_SHOW = "INFO_SHOW"
INFO_CHANGE = "INFO_CHANGE"
INFO_SEND = "SEND_INFO"
