"BASE"
BACK = "BACK"

"""MAIN MENU"""
SHARE_INFO = "SHARE_INFO"
MENU_ABOUT = "MENU_ABOUT"

"FORM"
FORM_MENU = "FORM_MENU"
COLLECT_DATA = "COLLECT_DATA"
EDIT_MENU = "EDIT_MENU"
SHOW_DATA = "SHOW_DATA"
SEND_DATA = "SEND_DATA"
