"""MAIN MENU"""
SHARE = 'SHARE'
ABOUT = 'ABOUT'
DONATION = 'DONATION'

"""HANDLERS PREFIX"""
FORM = 'FORM'
SELECT = 'SELECT'
ASK = 'ASK'

"""MENU"""
NAME = 'NAME'
DESCRIPTION = 'DESCRIPTION'
BUTTON_TEXT = 'BUTTON_TEXT'
LINK = 'LINK'
MODEL = 'MODEL'
FIELDS = 'FIELDS'
MENU = 'MENU'

"""FORM"""
INFO = 'INFO'
DATA = 'DATA'
SELECTED_OPTION = 'SELECTED_OPTION'
FIELD_INDEX = 'FIELD_INDEX'
FIELD_EDIT = 'FIELD_EDIT'

"""QUESTIONS"""
TITLE = 'TITLE'
TEXT = 'TEXT'
HINT = 'HINT'