"""MAIN MENU"""
SHARE = 'SHARE'
ABOUT = 'ABOUT'

"""HANDLERS PREFIX"""
FORM = 'FORM'
SELECT = 'SELECT'
ASK = 'ASK'

"""FORM"""
INFO = 'INFO'
DATA = 'DATA'
SELECTED_OPTION = 'SELECTED_OPTION'
FIELD_INDEX = 'FIELD_INDEX'
FIELD_EDIT = 'FIELD_EDIT'