"""MAIN MENU"""
SHARE = 'SHARE'
ABOUT = 'ABOUT'
DONATION = 'DONATION'

"""HANDLERS PREFIX"""
FORM = 'FORM'
SELECT = 'SELECT'
ASK = 'ASK'

"""MENU"""
BUTTON_TEXT = 'name'

"""FORM"""
INFO = 'INFO'
DATA = 'DATA'
SELECTED_OPTION = 'SELECTED_OPTION'
FIELD_INDEX = 'FIELD_INDEX'
FIELD_EDIT = 'FIELD_EDIT'