"""FORM KEYS"""

FORM = 'FORM'
SELECT = 'SELECT'
INPUT = 'INPUT'

INFO = 'INFO'
APPLICATION = 'APPLICATION'
QUESTION_INDEX = 'QUESTION_INDEX'
SELECTED_OPTION = 'SELECTED_OPTION'
EDIT_FIELD = 'MODIFYING_FIELD'