"""Remove id field from user_group association table.

Revision ID: 5aeecc3b5b62
Revises: 29b0ccf4f402
Create Date: 2024-12-05 18:05:46.861692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aeecc3b5b62'
down_revision: Union[str, None] = '29b0ccf4f402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_group', 'id')
    op.drop_column('user_group', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('message_group', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###