"""Change text field max length to 1500.

Revision ID: 4a118776ada6
Revises: e5db9cd6d15e
Create Date: 2024-12-21 11:27:31.115177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a118776ada6'
down_revision: Union[str, None] = 'e5db9cd6d15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###