"""Add auto-increment id and remove id from association table

Revision ID: 300f4835a87c
Revises: c04157089785
Create Date: 2024-11-26 10:12:18.598294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300f4835a87c'
down_revision: Union[str, None] = 'c04157089785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###