"""Change text field max length to 1000.

Revision ID: 3b627edb26a8
Revises: 4a118776ada6
Create Date: 2024-12-21 20:21:51.485189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b627edb26a8'
down_revision: Union[str, None] = '4a118776ada6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    # ### end Alembic commands ###