"""Add auto-increment id and remove id from association table

Revision ID: 9ee83545c17d
Revises: 300f4835a87c
Create Date: 2024-11-29 23:33:00.650241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee83545c17d'
down_revision: Union[str, None] = '300f4835a87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###