"""empty message

Revision ID: b6f239481bb3
Revises: 3b627edb26a8
Create Date: 2025-02-06 15:33:29.308860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f239481bb3'
down_revision: Union[str, None] = '3b627edb26a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_status',
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', name='message_status_enum'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_tg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('message_group', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('message_group', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_group', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('user_group', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_group', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('message_group', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('message_group', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_table('message_status')

    op.execute('DROP TYPE message_status_enum')
    # ### end Alembic commands ###