name: bot-providenie workflow

on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            repo="git@github.com:${{ github.repository }}.git"
            cd /home/${{ secrets.USER }}/
            [ ! -d "providenie" ] && git clone -b release $repo providenie 
            cd providenie
            git checkout release
            git pull
            echo TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" > .env
            echo SMTP_SERVER_PORT="${{ secrets.SMTP_SERVER_PORT }}" >> .env
            echo SMTP_SERVER_ADDRESS="${{ secrets.SMTP_SERVER_ADDRESS }}" >> .env
            echo SMTP_SERVER_BOT_EMAIL=${{ secrets.EMAIL_BOT }} >> .env
            echo SMTP_SERVER_BOT_PASSWORD=${{ secrets.EMAIL_BOT_PASSWORD }} >> .env
            echo EMAIL_CURATOR=${{ secrets.EMAIL_CURATOR }} >> .env
            echo LOG_LEVEL=${{ secrets.LOG_LEVEL }} >> .env
            docker compose --file docker-compose.yaml stop
            docker compose --file docker-compose.yaml rm bot -f
            docker compose --file docker-compose.yaml up --build -d