name: bot-providenie workflow

on:
  push:
    branches: [feature/ci_cd]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Uploading project files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: .
          target: /home/${{ secrets.USER }}/providenie

      - name: Building Docker image on remote server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /home/${{ secrets.USER }}/providenie
            sudo docker-compose stop
            sudo docker-compose rm providenie
            sudo rm -f .env
            touch .env
            echo TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" >> .env
            echo EMAIL_BOT=${{ secrets.EMAIL_BOT }} >> .env
            echo EMAIL_BOT_PASSWORD=${{ secrets.EMAIL_BOT_PASSWORD }} >> .env
            echo EMAIL_CURATOR=${{ secrets.EMAIL_CURATOR }} >> .env
            echo LOG_LEVEL=${{ secrets.LOG_LEVEL }} >> .env
            sudo docker build -t providenie:latest .
            sudo docker-compose up -d --build providenie